### ISSUE TITLE
Add username/password length validation

### ISSUE THREAD

**Issue by robobario** [robobario/gameswap#18]
I removed length validations from the database since username/password are not required fields in the case of google login.

We need the frontend to give proper feedback on lengths and the backend to reject signup/login attempts with small usernames and passwords.

Add some sensible max length too, find out what googles max name length is.

**Comment by mtokumaru** [comment]
I found google max passwords length is 100, first/last names 60. Didn't see anything for username, but maybe 60 is also a reasonable limit. We will also need a password reset mechanism at some point.
